name: Lint / Test / IT

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  kafkactl-version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run kafkactl-version-check
        run: make kafkactl-version-check

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        providers:
          - aws
          - azure
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: './${{ matrix.providers }}/go.mod'
      - name: Run Lint
        working-directory: ./${{ matrix.providers }}
        run: make lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        providers:
          - aws
          - azure
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: './${{ matrix.providers }}/go.mod'
      - name: Run Lint
        working-directory: ./${{ matrix.providers }}
        run: make test
